name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-golang-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-golang-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        run: |
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SERVER_SSH_KEY }}" > deploy_key
          chmod 600 deploy_key
          scp docker-compose.yml root@${{ secrets.SERVER_IP }}:/project/kttz/
          ssh -i deploy_key root@${{ secrets.SERVER_IP }} "cd /project/kttz && docker-compose pull && docker-compose up -d"
        env:
          DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
